experiments/rsc/scripts/configs/vite.mts
experiments/rsc/scripts/lib/constants.mts
experiments/rsc/scripts/lib/vitePlugins/transformJsxLinksTagsPlugin.mts

Currently, when building, when we see this in jsx:
```
<script type="module" src="/src/client.tsx"></script>
```
We turn this into:
```
<script type="module" src="/assets/name-of-corresponding-entry-chunk.js"></script>
```
However, we don't do the same for stylesheets:
```
<link rel="stylesheet" href="/src/app/style.css" />
```
This PR fixes that.

fix: Style resolving in production

---

experiments/rsc/package.json
experiments/rsc/postcss.config.js
experiments/rsc/scripts/configs/vite.mts
experiments/rsc/scripts/lib/getShortName.mts
experiments/rsc/scripts/lib/vitePlugins/asyncSetupPlugin.mts
experiments/rsc/scripts/lib/vitePlugins/miniflarePlugin/plugin.mts
experiments/rsc/scripts/lib/vitePlugins/restartPlugin.mts
experiments/rsc/scripts/runDevServer.mts

Adds a vite plugin that will restart the dev server if any configs change (any js, ts or json file in root dir or in `scripts/`).
* When a config file changes, close the dev server cleanly.
* Have the `pnpm dev` script in `package.json` re-run the script if it closed with a zero exit code => the user didn't Ctrl-C, and the script didn't exit with an error.
* Leverage Vite HMR browser client auto-retry capabilities to reload the page when the server is running again
Ideally we could just use vite's `server.restart()`. I wasn't able to get this working - I got some obscure C error from workerd and didn't investigate further. That said, I think restarting the actual process is likely more robust, we can be more sure in this case that we're running on the latest changes.

feat: Restart dev server on config changes

---

experiments/billable/package.json
experiments/billable/scripts/codegen.mts
experiments/billable/scripts/configs/vite.mts
experiments/billable/scripts/lib/vitePlugins/miniflarePlugin/plugin.mts
experiments/billable/scripts/lib/vitePlugins/restartPlugin.mts
experiments/billable/scripts/runDevServer.mts
experiments/billable/scripts/runWorkerScript.mts
experiments/billable/src/scripts/defineScript.ts
experiments/billable/src/scripts/seed.ts
experiments/rsc/scripts/codegen.mts

https://app.claap.io/na-58/c-qkcr0NJtVm-fWkblyclDUP8
* Allows us to write and run scripts that run _within_ the worker (inside the miniflare sandbox).
* Adds a `seed.ts` example script and changes `pnpm seed` to use it
* More context on the approach in [the video](https://app.claap.io/na-58/c-qkcr0NJtVm-fWkblyclDUP8
)!
Solves #34

feat: Support worker script runs + in-worker seed script

---

experiments/billable/package.json
experiments/billable/scripts/configs/vite.mts
experiments/billable/scripts/lib/vitePlugins/aliasByEnvPlugin.mts
experiments/billable/scripts/runDevServer.mts
experiments/billable/src/app/pages/invoiceDetail/FetchInvoice.tsx
experiments/billable/src/app/services/invoices.ts

I added a fix in #36 (https://github.com/redwoodjs/reloaded/pull/36/commits/44632d7973110fe4b72fd4037ff54e1cde31627f) that caused us to always resolve react to a custom build of react. This custom build caters for the fact that RSC and SSR are sharing a runtime.
However, I accidentally made the client side bundling also use this custom build of react, rather than normal react.
I've added a plugin that allows us to alias react to the custom build of react only for the worker side, but leave it alone on the client side.
While fixing this, I discovered that the current way of having RSC and SSR share a single react build will not work for all things. For example, if there is a `use()` call in SSR-rendered code, we will end up with an issue because RSC is expecting its `use()`` and not the …

fix: Fix client side

---

experiments/billable/scripts/lib/vitePlugins/miniflarePlugin/plugin.mts
experiments/textify/scripts/lib/vitePlugins/miniflarePlugin/plugin.mts

We invalidate the style module for the client environment when the worker has been updated -
since there may have been changes to class usages in the app code, which can result in differences to the stylesheet.
Problem is, the client environment might not yet have the style module in its module graph, so we need to check for that before trying invalidating.
Solves the issue where we see this during `pnpm dev`
```
[vite] Internal Server Error
Cannot read properties of undefined (reading 'invalidationState')
at EnvironmentModuleGraph.invalidateModule (/Users/justin/rw/reloaded/experiments/textify/node_modules/.pnpm/vite@6.0.0_@types+node@22.9.0_jiti@1.21.6_terser@5.36.0_tsx@4.19.2_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-C6qYk3zB.js:51820:39)
```

fix: Fix miniflare plugin HMR breaking on some updates

---

experiments/billable/package.json
experiments/billable/pnpm-lock.yaml
experiments/billable/scripts/lib/vitePlugins/miniflarePlugin/plugin.mts
experiments/billable/scripts/lib/vitePlugins/miniflarePlugin/runner.mts
experiments/billable/scripts/lib/vitePlugins/miniflarePlugin/types.mts
experiments/billable/scripts/runWorkerScript.mts
experiments/textify/package.json
experiments/textify/pnpm-lock.yaml
experiments/textify/scripts/lib/vitePlugins/miniflarePlugin/plugin.mts
experiments/textify/scripts/lib/vitePlugins/miniflarePlugin/runner.mts
experiments/textify/scripts/lib/vitePlugins/miniflarePlugin/types.mts
experiments/textify/scripts/runWorkerScript.mts
experiments/textify/src/worker.tsx

In order to get vite HMR and miniflare to work together, we need to have a wrapper entry point module, which will import and run the relevant code dynamically, leveraging vite dev server for loading the modules.
The way we were defining this wrapper was with a durable object. We exposed methods on the durable object for initialization (we need to create a vite "module runner" inside miniflare), as well as sending messages from vite into miniflare. This way, we can get at the "stub" of the durable object instance outside of miniflare, to call those methods via RPC. In other words, defining methods on a durable object and then calling them from outside of miniflare is one way to hook vite dev server up to code running inside of miniflare. This approach is what the vite team use in [their …

fix: Allow for cloudflare worker handlers other than fetch

---

experiments/billable/src/worker.tsx

* Vite sends an initial request to the worker when running the dev server, at which point the Prisma WASM is imported. Using the Prisma for the first time _after_ this initial request (e.g. if we only run the db for a request to /some/subpath) causes vite to not try import the WASM module at all, and ultimately the request ends up hanging indefinetely.
* However, once the WASM has been imported, it is cached in some way that persists on the file system (from experimentation, it is not in node_modules/.vite). This means that if you were to subsequently change the code to _not_ have Prisma used after the initial request, the WASM will still be cached and the request will not hang. This makes this issue particularly hard to debug.
* To work around this, we run a `SELECT 1` query via Prisma …

fix: Work around prisma WASM hang

---

experiments/textify/src/worker.tsx

Little fix where the chunking was not compiling the base64 properly again, now it works to send back the entire audio transcription

fix textify chinking bug

---

experiments/billable/src/app/pages/invoice/DetailPage/InvoiceDetailPage.tsx
experiments/billable/src/app/pages/invoice/ListPage/InvoiceListPage.tsx
experiments/billable/src/app/pages/invoice/routes.ts

We currently have an issue with `"use server"` modules where we cannot use `export default`s, only `export`s.
This PR avoids the issue by changing the relevant `export default`s to `export`s. #84 tracks solving the actual issue for future cases.

fix: Deploys for billable

---

experiments/billable/package.json
pnpm-lock.yaml
reloaded/package.json
reloaded/src/worker/db.ts

* Fix path to build vendor bundles script (it was outdated)
* `@ts-expect-error` for prisma client imports in reloaded (since client generated in application)
* Bring prisma cli back as billable dev dep

fix: Fix billable after refactoring out reloaded runtime

---

reloaded/src/vite/configPlugin.mts

After refactoring out reloaded runtime from billable, we now need to include react-server-dom-webpack in the optimized deps. I still need to figure out why, but in the meantime I'd like to unblock @peterp

fix: Include react-server-dom-webpack when optimizing deps

---

reloaded/src/worker/lib/router.ts

There's a .pop() in the route handler on the handlers array, causing reruns of the same request to yield different results.
Reproduction + demo of fix: https://www.loom.com/share/e9a01b74965e4c979a47f61f6cd87801

fix: Ensure route handler does not mutate handlers array

---

experiments/billable/package.json
reloaded/src/vite/configPlugin.mts
reloaded/src/vite/customReactBuildPlugin.mts
reloaded/src/vite/redwoodPlugin.mts

We use a custom react build on cloudflare workers so that we can do RSC and SSR in the same runtime.
I accidentally had us using this same build for the client side too.
This PR makes it so that we only resolve to the custom build if we are in the worker environment.

fix: Only use custom react build for worker

---

sdk/src/vite/useClientPlugin.mts

Part of our 'use client' transformations for worker-side code involves renaming components to include an `SSR` suffix. The way we were (I was) doing this was naiive - we'd basically do a `replaceAll()` for the components name 🙈. So if you had "Word" as a component name, and it had copy "Word" in it, both the component name (expected) and the copy (unexpected) would be transformed to "WordSSR". This in turn would cause a react hydration issue since the SSR'd code would render this copy, while the client side code would still render "Word".
We already know the line+column positions of the export we want to add the suffix too, we just need to use it.

fix: SSR component transformation for 'use client'

---

sdk/src/runtime/register/worker.ts
sdk/src/runtime/worker.tsx

When rendering page components (the "root" component for a page), we provide it with props that includes `env`. This is fine when the page component is a worker-rendered RSC component, but not fine when the page component is a `use client` component - in the latter case, we are exposing `env` to the browser.
Detect if page component is a client component. If it is, pass only `params` and `ctx` as props.
**note** We still need to be careful to not provide anything in ctx that we do not want shown to the browser. I'm not sure if it would be better for us to not pass `ctx` down either. But then we maybe want to prevent page components from being `use client` components in the first place. Or maybe we can make it clear in docs that ctx passed to client side?

fix: Avoid env exposure for client-based pages

---

sdk/src/runtime/lib/auth/session.ts
starters/passkey-auth/src/app/pages/auth/LoginPage.tsx
starters/passkey-auth/src/app/pages/auth/routes.ts
starters/sessions/src/app/pages/auth/routes.ts

There were two issues:
1. there was an issue in the session cookie creation logic which was causing it to not set `maxAge` to `0` when removing the cookie
2. the auth starters were not `await`-ing `session.remove()`

fix: Logout for auth starters

---

sdk/src/runtime/lib/router.ts
starters/passkey-auth/src/app/pages/auth/routes.ts
starters/passkey-auth/src/worker.tsx
starters/sessions/src/app/pages/auth/routes.ts
starters/sessions/src/worker.tsx

The session and passkey-auth starters had a bunch of unnecessary passing of `Context` param to route API methods, for example:
```ts
export default defineApp<Context>([
async ({ env, ctx, request }) => {
setupSessionStore(env);
ctx.session = await sessions.load(request);
},
// >>> Context here not needing to be passed
layout<Context>(Document, [
index([
Home,
]),
// >>> also here
prefix<Context>("/user", authRoutes),
])
])
```
At some point we needed these, but we don't seem to need it anymore (without losing type information). TBH I'm not sure what changed, but glad we don't need to do this anymore regardless.
We were needing add explicit type annotations for arrays of routes, in order for ts to accept them being provided as part of `defineApp`, e.g.
```ts
const authRoutes: …
```

fix: Avoid unnecessary passing of Context type param for routes

---

sdk/src/vite/useClientPlugin.mts

Part of our 'use client' transformations for worker-side code involves renaming components to include an `SSR` suffix. After #126, we do this transformation by locating the line+column where the `export` is. This is fine for inlined exports (`export function Foo() {...}`) but breaks for grouped exports (`function Foo() {}; export { Foo }`).
Find where the function is defined and replace it there.

fix: Fix useClient transform for non-inlined exports

---

sdk/src/vite/customReactBuildPlugin.mts

#144 fixed usage of react builds for the new redwoodsdk package for the `vite dev` case. We needed to have the same fix apply also for `vite build` for deployments.

fix: Ensure custom react build is copied in deployments too

---

starters/drizzle/README.md
starters/passkey-auth/README.md
starters/prisma/README.md
starters/sessions/README.md

Now that we have a `redwoodsdk` package on npm that our starters use, we need to update their READMEs: users no longer needs to git clone the repo and create a project in the workspace - they can now create it anywhere they like.
This also brings an opportunity for us to use [degit](https://github.com/Rich-Harris/degit) - a natural way to scaffold using what we already have in our repo's starters.
- Replaced complex SDK build and workspace setup instructions with simple `degit` commands
- Updated all starters to use the same project creation pattern:
```shell
npx degit redwoodjs/sdk/starters/<starter-name> my-project-name
cd my-project-name
pnpm install
```
- Used Prisma starter's README as the template
- Consistent sections across all starters:
- Brief description
- Setup steps
- …

docs: Add README updates after redwoodsdk published

---

sdk/src/runtime/lib/auth/session.ts

Fixes #140 
* In dev, we exclude `Secure` from cookie attributes
* We now allow for custom cookie definition for sessions
```ts
const sessionStore = defineDurableSession({
// ...
cookieName: "user_session",
createCookie: ({ name, sessionId, maxAge }) => `${name}=${sessionId}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge ?? (7 * 24 * 60 * 60)}`
});
```

fix: Cookies should not be Secure in dev

---

sdk/bin/rw-scripts.mjs
sdk/src/scripts/migrate-new.mts

We have a script runner (`rw-scripts.mjs`) for running scripts we define in the sdk (e.g. `migrate:new`). This runner was hardcoded to use the sdk's `src` scripts, with the idea being we'd remove that hardcoding once we release the sdk. I just forgot to actually do that 🤦

fix: Resolve to build script paths

---

experiments/billable/package.json
experiments/cutable/package.json
experiments/yt-dos/package.json
experiments/zoomshare/package.json
starters/drizzle/package.json
starters/minimal/package.json
starters/passkey-auth/package.json
starters/prisma/package.json
starters/sessions/package.json

Early implementations of the sdk relied on us having `vite dev` in a ` while true` bash loop, as a way to ensure changes to configuration restarted the dev server.
We don't need this anymore, but the starters still have this remnant around. This PR removes it so that `pnpm dev` is basically `pnpm vite dev`

fix: Avoid while loop for `pnpm dev`

---

sdk/src/vite/invalidateViteDepsCacheEntry.mts
sdk/src/vite/redwoodPlugin.mts

We need to use vite optimizeDeps for all dependencies to work with @cloudflare/vite-plugin. The thing is, @prisma/client has generated code, so users end up with a stale @prisma/client when they change their Prisma schema and regenerate the client until they clear out node_modules/.vite. We can’t exclude @prisma/client from optimizeDeps since we need it there for @cloudflare/vite-plugin to work, but we can manually invalidate just its own dependencies cache entry.

fix: Invalidate prisma client optimizeDeps cache entry when running vite dev

---

starters/passkey-auth/README.md
starters/passkey-auth/wrangler.jsonc
starters/sessions/README.md
starters/sessions/wrangler.jsonc
starters/standard/README.md
starters/standard/wrangler.jsonc

Removes secret keys from starters' `wrangler.jsonc` configs, and documents in READMEs how to add these instead in dev and deployments.

fix: Avoid placeholder keys in wrangler.jsonc

---

docs/src/content/docs/core/authentication.mdx

Similar to the other core docs, we should have a setup section to get the user started

docs: Add setup to auth docs

---

sdk/src/vite/useClientPlugin.mts

Previously, our `useClientPlugin` only supported inline exports (e.g., `export function Component()` or `export const Component = ...`). However, it didn't properly handle grouped exports (e.g., `export { Component, OtherComponent }`). This limitation meant that components using grouped exports weren't being properly transformed for client/server rendering.
This PR enhances the `useClientPlugin` to support both inline and grouped exports:
1. We now identify all function exports and track which ones were inline exported
2. For each function, we:
- Rename it with an SSR suffix
- Add a client reference registration that uses the original name
3. We export all SSR versions at the end of the file
4. We only re-export functions that were originally inline exported (since grouped exports are …

fix: Support grouped exports with "use client"

---

docs/astro.config.mjs
docs/src/content/docs/core/security.mdx
sdk/src/runtime/lib/router.ts
sdk/src/runtime/worker.tsx
starters/drizzle/src/app/headers.ts
starters/minimal/src/app/headers.ts
starters/passkey-auth/src/app/headers.ts
starters/prisma/src/app/headers.ts
starters/sessions/src/app/headers.ts
starters/standard/src/app/headers.ts

* Adds basic security docs explaining what headers we set, where to find them, how to work with them, and how to change them.
* Updates starter headers to allow for inline styles: workerd seems to add them for `Response()`s + it is arguably an acceptable tradeoff to allow for inline styles (compared to inline scripts, for e.g.)
* Allow layouts (e.g. `Document`) to take in a nonce - users will likely need this for their inline scripts

feat: Security docs + updates to starter headers + pass nonce to layouts

---

sdk/src/vite/useClientPlugin.mts
sdk/src/vite/useClientPlugin.test.mts

We were double-including the SSR exports, and had false positive tests for this

fix: useClientPlugin for inline exports

---

sdk/src/vite/useClientPlugin.mts
sdk/src/vite/useClientPlugin.test.mts

There was a bug in how we were transforming "use client" modules for the case of `export default function`

fix: export default function for "use client"

---

sdk/src/runtime/lib/router.ts

We were setting the default type for route params to `Record<string, string>`, and then not providing type params across the relevant types for `route()`. This means that instead of ts being able to infer the type for params from the component passed to `route()`, ts would compare the type for params for the component to `Record<string, string>`, (e.g. for `const Component = (props: RouteContext<Context, { foo: string }>) => ...` to would compare `{ foo: string } `to `Record<string, string>`).
* Provide type params for route params across relevant types for `route()` - to make inference possible
* For types that contain multiple routes (.e.g `layout`), use `any` as a default for the route params - since it might be more technically correct if we can get ts to infer the type for params to …

fix: Default type for route params shouldn't prevent more concrete types

---

sdk/src/runtime/lib/router.ts

We use type params on our router API methods so that ts can infer the relevant types (e.g. context, params) for routes, based on their corresponding middleware or components.
It isn't always clear enough what types to infer though. For example, if routes arrays are defined without telling ts explicitly what the types are for the array. In the case below, when `authRoutes` is passed to `prefix()`, ts will take its type to be `RouteDefinition<unknown, unknown>[]`. `unknown` doesn't match to `Context`, causing type errors.
```ts
export const authRoutes = [route('/login', Login), route('/user/logout', () => {...}]
type Context = {...}
defineApp<Context>([
prefix('/user', authRoutes)
])
```
Default the values for type params to `any`. If ts is able to infer the types, they're sued instead of …

fix: Set defaults for type params for router API methods

---

docs/src/content/docs/core/routing.mdx
sdk/src/runtime/lib/router.ts
sdk/src/runtime/worker.tsx

In addition to `request` and `env`, CF also provide `ctx`: https://developers.cloudflare.com/workers/runtime-apis/context/
This PR adds the API methods in CF's `ctx` (the "execution context") to our `RouteOptions`:
```ts
const app = defineApp([
({ request, env, cf }) => {
cf.waitUntil()
}
])
```

feat: Include CF exec context in RouteOptions

---

sdk/src/scripts/patchInspectorPort.mts
sdk/src/scripts/worker-run.mts

We run our seed scripts using Miniflare (via Cloudflare's Vite plugin) to simulate a deployed Worker environment. These scripts are used in pnpm seed as well as in postinstall hooks across our starters to ensure D1 databases are correctly migrated and seeded.
Miniflare launches an inspector on port 9229 and internally spawns a workerd child process. We previously patched net.Server.prototype.listen to rewrite attempts to bind to 9229 so they instead use an OS-assigned port (0), resolving port conflicts during concurrent script execution.
Despite resolving port conflicts, the process would still sometimes hang after completing its work. By inspecting process._getActiveHandles(), we identified two remaining sources of lingering activity:
-  **Open WebSocket clients**, likely created by …

fix: Hanging postinstalls (some more)

---

pnpm-lock.yaml
sdk/package.json
sdk/src/vite/useClientPlugin.mts
sdk/src/vite/useClientPlugin.test.mts

For `"use client"`, the sdk works for inlined `export` (e.g. `export const function Component() {}` and grouped exports `export { Component }`, but does not work for `export default cases`. This PR gets it working with the export default cases.
Up until now, we've been using regexes as a way to do the necessary transformations for `use client`. This was fine in the beginning, but in order to cater for all the different kinds of export cases (grouped exports, inlined exports, grouped default exports, inlined default exports, and for each of those for arrows, functions, and for each of those sometimes anoynmous, sometimes not), it has grown in complexity to the extent that regexes are no longer a reliable way of extracting the necessary information and transforming the code, and its just …

fix: `export default` cases for "use client"

---

sdk/src/runtime/lib/realtime/durableObject.ts

Our realtime durable object currently stores client info (the client's url, id, and cookie header for auth) as an attachment to the relevant socket using cloudflare's API for this: https://developers.cloudflare.com/durable-objects/best-practices/websockets/#serializeattachment
There is a limit of 2048 bytes for this attachment, so if the url and/or cookie header are large, the client info is easily larger than this limit and we end up with an error message.
Store only the client id as an attachment, and use the durable object's storage API to persist the relevant client info for that client id (across evictions). We also keep an in-memory cache around to save us needing to go to storage unnecessarily.
Include a long value in the url (e.g. `?<long_value>`) for the realtime POC: …

fix: A WebSocket 'attachment' cannot be larger than 2048 bytes

---

sdk/src/scripts/migrate-new.mts

- Change format for specifying name.
- Generate Prisma client if migration is applied.
Fixes #205

Improve "migrate:new" usability.

---

sdk/src/vite/useClientPlugin.mts

We are accidentally now dropping source maps if we see `'use client'` but its not the worker environment.

fix: Dropped source maps for use client when not worker environment

---

sdk/src/runtime/client.tsx

When introducing the realtime API, I accidentally broke updates for our normal fetch-based client.
Underlying reason: the function for setting the rsc payload gets updated, but we only look at initial value rather than the current one.
Thank you for finding this @peterp!

fix: RSC updates for fetch transport

---

sdk/src/vite/redwoodPlugin.mts

We used to automatically copy `.env.example` to `.env`, and symlink `.env` to `.dev.vars`.
And then I accidentally removed the line that does this: https://github.com/redwoodjs/sdk/pull/210
This PR brings it back.

fix: Bring back .env symlinking+copying

---

sdk/src/runtime/worker.tsx

We don't provide a default client.tsx so we shouldnt have the default document reference one.

fix: Default document should not have src/client.tsx script

---

sdk/src/vite/redwoodPlugin.mts

Users needing to run `pnpm wrangler types` is an extra step they need to think about that they arguably shouldn't need to. This PR makes it so that `pnpm wrangler types` is done as a step on `pnpm dev` inside the redwood plugin.

fix: Rerun wrangler types on pnpm dev

---

sdk/package.json
sdk/src/runtime/lib/realtime/client.ts
sdk/src/runtime/lib/realtime/durableObject.ts
sdk/src/scripts/debug-sync.mts

In our realtime API, there are two cases where need to update the UI with a new RSC payload stream:
* 1. rsc update: a change issued by a different client (or by server) has  resulted in a new rsc payload
* 2. action result: a client called an action, so it gets a new rsc payload, including the UI update and action result
We were only setting a new payload stream in case 1 and not case 2.
Our note taking demo did not catch this, since the text was already being changed client side since it was a text box!

fix: Realtime updates given in action responses

---

docs/src/content/docs/core/security.mdx
sdk/README.md
sdk/package.json
starters/minimal/README.md
starters/passkey-auth/README.md
starters/sessions/README.md
starters/standard/README.md

There were a few places where we (I) said RedwoodJS when I meant RedwoodSDK

chore: Renames JS->SDK

---

docs/src/content.config.ts
docs/src/styles/custom.css

Adds a preview banner that says "RedwoodSDK is in preview mode." at the top of every page of the documentation:

✨ Added a preview banner

---

docs/src/content/docs/core/database.mdx

fixes #260 by pointing to the standard starter instead of the (removed) prisma one

fix (docs): Update documentation to point to Standard instead of prisma

---

sdk/src/runtime/lib/router.ts
sdk/src/runtime/requestInfo/types.ts
sdk/src/runtime/requestInfo/worker.ts
sdk/src/runtime/worker.tsx

Now with #251, the sdk's router runtime code imports code in the module where `requestInfo` is defined, which in turn uses async_hooks (a node API, which CF also supports and polyfills). The problem comes in when client side code tries import `@redwoodjs/sdk/router` - when it needs to do to use `defineLinks()` (valid for that to be client side). As a result, the client side tries import async_hooks.
Avoid imports requestInfo module in router

fix: Avoid worker import in router

---

sdk/src/runtime/entries/worker.ts
sdk/src/runtime/lib/router.ts
sdk/src/runtime/requestInfo/worker.ts
sdk/src/runtime/worker.tsx

Ever since #267, we've been exporting `RequestInfo` as a `type` rather than an `interface`, which breaks type augmentation of `DefaultAppContext` for it.

fix: AppContext type augmentation

---

sdk/src/scripts/migrate-new.mts
sdk/src/scripts/worker-run.mts
sdk/src/vite/redwoodPlugin.mts

In #255, we changed the sdk to not assume projects use pnpm. There were still some `pnpm` remnants around in the sdk, this PR removed those.
Fixes #296

fix: Remove remaining pnpm script runs

---

docs/src/content/docs/core/hosting.mdx

Fixed formatting on the **Core > Deploy Docs**

Update formatting for Deploy Docs

---

docs/README.md
docs/src/content/docs/core/authentication.mdx
docs/src/content/docs/core/database.mdx
docs/src/content/docs/core/queues.mdx
docs/src/content/docs/index.mdx

1. Added README style notes for code blocks with commands. 
2. Updated code blocks with commands to be more consistent. 
I wasn't really happy with the way this turned out, but I added it anyway. When previewed, the code blocks render as markdown, when I was really trying to show them as text. But, if someone looks at them in an editor, then they will see it as intended. 
Added withOutput to commands showing output:
Removed numbers from command blocks:
Added 'terminal' styling where missing:
Note: with all three style updates, i did not introduce any new formatting options. These styles already existed, they were simply applied inconsistently. For instance, I got the style for the command with output from the storage setup page.

(docs): updated code blocks for consistency

---

starters/minimal/types/rw.d.ts

It looks like I left the `rw.d.ts` in a broken state for minimal starter - updated minimal's `rw.d.ts` to match what we do for standard starter.

fix: DefaultAppContext in minimal starter

---

pnpm-lock.yaml
sdk/package.json
sdk/src/runtime/lib/router.ts
sdk/src/vite/injectHmrPreambleJsxPlugin.mts
sdk/src/vite/transformJsxScriptTagsPlugin.mts
starters/minimal/package.json
starters/minimal/src/app/Document.tsx
starters/standard/package.json
starters/standard/src/app/Document.tsx

While testing client interactivity during RSC streaming, we encountered a delay in hydration with the following layout:
```
export function Home({ ctx }: RequestInfo) {
return (
<div>
<Counter />
<Suspense fallback={<Loading />}>
<Todos />
</Suspense>
</div>
);
}
```
In this setup:
-   <Counter /> is a client component rendered before the Suspense boundary
-   <Todos /> is rendered within the boundary
-   The HTML shell is flushed early and includes a <script type="module" src="/src/client.tsx"> intended to hydrate the app
* * * * *
Despite being flushed early, the module script does not execute until after the full document has streamed --- including Suspense resolution and the $RC(...) patch. As a result, hydration is delayed and interactivity for components like <Counter /> is …

fix: Ensure early client hydration during RSC streaming by avoiding type="module" deferral

---

sdk/src/vite/useClientPlugin.mts
sdk/src/vite/useClientPlugin.test.mts

The only thing we have to keep in mind is that this has to be the top of the file, if they add a comment and then `"use client";` it'll break.
Closes #269

Ensure that "use client" is not accidentally transformed.

---

starters/minimal/src/app/Document.tsx
starters/standard/src/app/Document.tsx

Should have been done in #320, slipped my mind.
See #320 for context.

fix: Move entry point <script> to <body> in starters

---

sdk/src/vite/transformJsxScriptTagsPlugin.mts
starters/minimal/src/app/Document.tsx
starters/standard/src/app/Document.tsx

Slight improvement on #320 and #323 - now that we have the entry point script in the <body> in starters (see #320), ideally we can start downloading these scripts asap - especially considering we are rendering in streaming fashion.
This PR:
* Adds a preload link to the entry point scripts to the starters
* Changes our transform plugin that looks replaces script src with built asset path, to do the same for preload links for scripts

feat: Preload entry point

---

sdk/src/runtime/render/transformRscToHtmlStream.tsx
sdk/src/runtime/worker.tsx

React's SSR renderer supports a nonce option, which is used for inline scripts added by react, e.g. for suspense boundaries (to "fill in" their results once suspense resolved). This PR passes the CSP nonce the sdk generates to react so that these inline scripts aren't blocked.

feat: Pass CSP nonce to react SSR renderer

---

docs/src/content/docs/getting-started/quick-start.mdx

For deploying to production, we use the dir name to name the worker and replace `__change_me__` automatically when the user runs `pnpm release`. So we don't need that step in quick start anymore :)

Remove name change step in quick start

---

docs/src/content/docs/core/overview.mdx

We had an aside in the core docs overview mentioning that quick start using minimal starter but core uses standard. We're bcak to using standard starter in quick start so removing the aside.

Remove aside re minimal starter

---

sdk/src/scripts/ensure-deploy-env.mts
starters/standard/src/session/store.ts

In our deployment script, we check if the codebase has webauthn references, and only then set the relevant vars. At the moment this also includes `AUTH_SECRET_KEY` - but this is problematic since an application might have no webauthn but still reference `AUTH_SECRET_KEY`.
This PR fixes this by checking and handling for AUTH_SECRET_KEY separately in the deployment script.

fix: Separate webauthn vars for auth secret key vars in deployment script

---

sdk/src/scripts/ensure-deploy-env.mts

In #329, we're looking for an `AUTH_SECRET_KEY` when deciding whether to set it during deployment. Except we no longer require this var to be specified in user app (we look it up in the sdk itself). What we _should_ be looking for, is imports to `@redwoodjs/sdk/auth`. That's what we change in this PR.

fix: Check for sdk/auth import in deploy script

---

sdk/src/vite/reactConditionsResolverPlugin.mts

#331 moves the react deps to the sdk, which required some custom resolving (see #331 description for more context on that). For `react-dom/server.edge`, we were only resolving correctly in production - in dev we were resolving to whatever `require('react-dom/server')` would resolve to, which differs to what the other react deps would be expecting in the context of edge+development.

fix: react-dom/server.edge resolving in dev

---

starters/standard/.cursor/rules/rwsdk-interruptors.mdc
starters/standard/.cursor/rules/rwsdk-middleware.mdc
starters/standard/.cursor/rules/rwsdk-react.mdc
starters/standard/.cursor/rules/rwsdk-request-response.mdc

This PR updates the meta info associated with a few cursor rules in the starters kit.
Specifically, it adds descriptions and sets when to attach based on globs.
Several globs (such as the requests) did not match in an app and thus would show:
Now, the globs should match and auto attach better when found.

(starters): Updates cursor rule meta info

---

README.md

The issue is that markdown syntax doesn't work inside HTML tags. When you have HTML tags like `h1`, the content inside them is treated as HTML, not markdown. So the markdown link syntax 
```
[Cloudflare](https://www.cloudflare.com/)
```
won't be processed as a link.
Uses standard anchor.

README: Fixes readme link rendering in main title heading

---

pnpm-lock.yaml
sdk/package.json
sdk/src/vite/configPlugin.mts
sdk/src/vite/reactConditionsResolverPlugin.mts
starters/minimal/package.json
starters/standard/package.json

In order to have control over the react versions we use (while RSC is stabilizing), we maintain the react versions in the sdk package itself rather than users having react packages as deps in their own apps. To accomplish this involves needing to tell vite that when doing `optimizeDeps` (since we need to de-cjs-ify react packages), that it should look for these deps as deps of the sdk instead. More on this in the initial PR where this was introduced - #331
In the initial PR where this was introduced (#331), we used some complicated logic of our own for determining which react package to use. We needed this to have control over when to use the packages that correspond to `react-server` import conditions vs not. There were bugs in this implementation that (for one) were causing us to …

fix: React dep resolution should respect import conditions correctly

---

sdk/src/runtime/worker.tsx

#342 added support for throwing responses to bubble them up in the component tree. What we (I) didn't handle, was throws that happen at the Page (root) level. This PR makes sure both cases are covered.

fix: Catch errors that Page-level throws

---

sdk/src/runtime/worker.tsx

Since #342, we call page functions rather than letting react unroll the element tree from that level, in order to check whether the result is a response or an element.
Problem is, the Page function may be a `use client` component, in which case:
* it will never be able to return a `Response`
* The hooks that need to work in the context of ssr (e.g. `useState()`) are not set to use the correct internal react state used by ssr) if called as a function like this
To solve this, we avoid calling page functions if they are client component (since we won't be getting a `Response` from them anyways).

fix: Skip calling Page functions for client references

---

sdk/src/vite/useClientPlugin.mts
sdk/src/vite/useClientPlugin.test.mts

When transforming `use client` modules for worker environment
* we keep the original components code as the SSR form the components (and export under name `<Component>SSR`) - this is used for SSR rendering
* we transform the existing component exports to instead be registered client references (since the actual component code is only relevant to client environment)
In #346, we fixed the transformations we were doing for grouped exports via making the code more robust, by collecting all info we need before doing any transformation. Except in attempting to make it more robust I introduced a new regression for the `export default case`, since we are now getting some info _after_ transformation for that case.
Ensure we are _actually_ collecting everything we need before transformation, to …

fix: Avoid info collection after transforms for use client export defaults

---

sdk/src/runtime/worker.tsx

Since #342, we call page functions to unroll the first level, rather than creating an element for react to unroll later. We do this to determine whether the page returned an element or not.
This had an important implication for the way we do RSC: We are now calling the page function _before_ handling actions, whereas previously this would only happen _after_ handling actions (indirectly, via react).
Make sure action handling always happens first.
We should maybe re-consider whether we do in fact want page functions to either return an element or response. A subtle implication is that we are effectively needing to unroll the first step in the component tree. That should be react's job, and bad things might happen if we are doing it ourselves. e.g. react has not yet set up its internal …

fix: Ensure we always handle actions before re-rendering

---

pnpm-lock.yaml
sdk/package.json
starters/minimal/package.json
starters/standard/package.json

Allows @prisma/{client,engine}, prisma, esbuild, sharp (dep of workerd), and workerd builds scripts during pnpm install for starters
Solves #358

chore: Allow selected build script in starters

---

docs/src/content/docs/core/queues.mdx
docs/src/content/docs/core/storage.mdx

When playing around with the sdk I noticed some docs that reference the usage of `env` via the `RequestInfo`. Trying to use this code gives a TS error: `Property 'env' does not exist on type 'RequestInfo<any, DefaultAppContext>'`.
I replaced the usage with this with the import of the `env` from `cloudflare:workers`

fix env usage in docs

---

docs/src/content/docs/core/storage.mdx

I often forget the different naming conventions with CF: R2 is different than Queues etc.
This adds a section on what valid R2 bucket names can be.

docs: Storage - added section on naming

---

docs/src/content/docs/core/queues.mdx

I followed the codes, but Cloudflare/Wrangler enforcing naming rules, so the `QUEUE_NAME` example (while a placeholder) if a dev tries it they will get an error:
```
🌀 Creating queue 'MY_QUEUE_NAME'
✘ [ERROR] A request to the Cloudflare API (/accounts/xxxx/queues) failed.
Queue name 'my_queue_name' is invalid: invalid queue name: MY_QUEUE_NAME. Must match
^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$. [code: 11003]
If you think this is a bug, please open an issue at:
https://github.com/cloudflare/workers-sdk/issues/new/choose
```
Queues names cannot contain capital letters or underscores.
Note: Bindings can and a good practice is to have them standout like `MY_QUEUE_NAME`
Next, I updates the receiving messages section to include two ways to know which q you're handling the message:
1. Look at the …

docs: Queues - Explain queue naming and receiving patterns

---

starters/minimal/.gitignore

ignore .wrangler directly even if the minimal starter doesn't need it by default

minimal-starter: ignore .wrangler

---

starters/minimal/src/worker.tsx
starters/minimal/tsconfig.json

small update to make the alias match between the minimal starter and the standard one.
the idea is to make the documentation work for both (especially for the [shadcn/ui](https://docs.rwsdk.com/guides/frontend/shadcn/) docs) that uses the alias heavily due to the nature of shadcn/ui

minimal-starter: update import paths to match standard starter

---

docs/src/content/docs/core/authentication.mdx
docs/src/content/docs/core/database.mdx

Fix 404 for relative links to [Quick Start Guide](https://docs.rwsdk.com/getting-started/quick-start/) on: 
- https://docs.rwsdk.com/core/database/
- https://docs.rwsdk.com/core/authentication/

Fix 2 docs links to Quick Start 

---

starters/standard/wrangler.jsonc

When we deploy, we look for `__change_me__` for various fields in the wrangler config and automatically replace these.
Except for standard starter, I accidentally checked in those changes. This PR reverts the values back to `__change_me__` there

fix: Use __change_me__ in standard starter config

---

pnpm-lock.yaml
sdk/package.json
sdk/src/vite/transformJsxScriptTagsPlugin.mts
starters/minimal/package.json
starters/standard/package.json

We have two vite environments: `client` (for client side) and `worker` (for code run in cloudflare worker).
The build step of `worker` relies on the build manifest vite generates for `client` - this asset includes mappings from the entry point source paths to their corresponding built destination paths.
It relies on the manifest so that we can replace references to client entry points in jsx (e.g. in `Document.tsx`) with their corresponding built assets.
We read the client manifest from disk the first time, then hold onto it in memory and use the in memory value instead for subsequent attempts to read it. However, when reading the client manifest, we do not check whether the current context is the `worker` environment (not the `client` environment). This causes two issues:
* if this is …

fix: Client entrypoint 404s

---

sdk/src/vite/checkIsUsingPrisma.mts
sdk/src/vite/redwoodPlugin.mts

We check whether the project is using prisma in order to apply build configuration specific to prisma - largely around getting prisma query engine wasm to work with deploys to cloudflare when using `@cloudflare/vite-plugin`.
The way we (I) checked whether the project is using prisma was pretty awful: `pnpm prisma --version`
* If you're not using pnpm or corepack, we'll incorrectly take it that you're not using prisma
* If for some reason you have a prisma global install but aren't using prisma for you're project, we'll incorrectly take it that you are using prisma
* There's probably further ways this check can break
Check whether the project has `@prisma/client` as an installed dependency by trying to resolve it (using https://www.npmjs.com/package/enhanced-resolve). If it can be …

fix: More robust check for prisma at build time

---

starters/standard/src/app/shared/links.ts

The standard starter only had shared links for the homepage. I updated the links to include `/user/login` and `/user/logout`.

standard-starter: updated shared links to include auth pages

---

pnpm-lock.yaml
sdk/package.json
sdk/src/vite/useClientLookupPlugin.mts
starters/minimal/package.json
starters/standard/package.json

On deploys/builds, RedwoodSDK scans for "use client" directives to build a lookup map used for dynamically importing client-only modules. This is needed for codesplitting to load them correctly in production.
The old version used a `grep` subprocess to find files. This worked locally but consistently failed in GitHub Actions — particularly with Cloudflare’s PR deploy setup. When that happened, the lookup map was empty and led to runtime errors like:
```
No module found for '/src/app/components/SomeComponent.tsx'
```
Not sure exactly why `grep` failed — could be anything from missing binaries to BusyBox behaviour or quoting issues in the container. Either way, it was brittle. Also, the approach was wrong to begin with since it matched "use client" anywhere in a file, not just where it …

fix: Avoid grep for 'use client' scan

---

sdk/src/lib/smokeTests/browser.mts
sdk/src/lib/smokeTests/cleanup.mts
sdk/src/lib/smokeTests/reporting.mts
sdk/src/lib/smokeTests/state.mts
sdk/src/lib/smokeTests/templates/SmokeTest.template.tsx
sdk/src/lib/smokeTests/templates/SmokeTestClient.template.tsx
sdk/src/lib/smokeTests/templates/smokeTestFunctions.template.ts

Our smoke tests verified initial server rendering and client-side functionality separately, but did not verify that server components would re-render in response to client-side actions.
We now implement a complete verification flow that:
1. Checks the initial rendered server component state
2. Invokes a client-side action that updates shared state
3. Verifies both the client-side result AND that the server component has properly re-rendered with the updated state

feat: Smoke tests check server render

---

docs/astro.config.mjs
docs/package.json
pnpm-lock.yaml

This PR adds the following LLM-friendly content:
1. /llms.tx
2. /llms-small.txt
3. /llms-full.txt
This can be used to provide better information to LLM's for using our codebase
For now we are using a plugin, I have been working on a manual method, but realise this will be hard to maintain and become outdated. 
Todo: I will test the effectiveness of the /llms-full.txt with LLM's once live.

add LLM-friendly content

---

docs/src/content/docs/tutorial/full-stack-app/2-create-app.mdx

This is a small fix to the full stack tutorial which mistakenly uses https rather than http for localhost links. If you click the existing links you'll experience an error locally

Fix https to http for localhost in full stack docs

---

docs/src/content/docs/guides/frontend/tailwind.mdx
docs/src/content/docs/tutorial/full-stack-app/2-create-app.mdx

The Tailwind install directions had highlighted the `environment` addition, but they weren't green, making it easy to overlook:
I changed the lines to be green:
The Tutorial, Tailwind install had green lines, 
but, I updated so that the two examples match.

📝 docs: Adjusted the Tailwind install formatting

---

starters/standard/src/db.ts
starters/standard/src/scripts/seed.ts
starters/standard/src/worker.tsx

In March, the [Cloudflare team added support](https://developers.cloudflare.com/changelog/2025-03-17-importable-env/) for importing bindings like `env` directly.
This allows us to initialise `PrismaClient` at the module level, making the Prisma WASM immediately available when the worker starts. That prevents the first request from hanging (as noted by @justinvdm).
This change tripped me up while integrating Better-Auth, since I used this starter as the base.

standard-starter: Initialise Prisma using env import

---

pnpm-lock.yaml
sdk/package.json
sdk/src/vite/__snapshots__/useServerPlugin.test.mts.snap
sdk/src/vite/useClientPlugin.mts
sdk/src/vite/useClientPlugin.test.mts
sdk/src/vite/useServerPlugin.mts
sdk/src/vite/useServerPlugin.test.mts

This PR rewrites the way that we're matching "use server"; in the worker and client. It now supports default exports:
Depends on #452
```
"use server"
export default function sum() {
return 1 +1
}
```
becomes:
```
"use server"
export function sum() {
return 1 +1
}
export default sum
```
@justinvdm 
Tests:
@justinvdm Can you think of any patterns that I'm missing?

RSC directives, support default exports in server components.

---

starters/standard/src/db.ts
starters/standard/src/worker.tsx

For prisma-client-js generator or cases where there are dynamic import to the prisma wasm modules, we need to make sure we are instantiating the prisma client later in the flow when the wasm would have been initialized.
Fixes regression introduced in #443 that appears when querying in a deployed app
```
ReferenceError: Cannot access 'UL' before initialization
```

Ensure prisma client initialized after wasm engine initialized

---

docs/src/content/docs/guides/email/2-email-templates.mdx

This PR fixes a small typo in the documentation file:
docs/src/content/docs/guides/email/2-email-templates.mdx

docs: Remove unneccessary word "is" in the email-templates doc"

---

sdk/src/runtime/lib/router.ts

When using the `layout()` function with route components marked as `"use client"`, the application would throw a serialization error as per this issue #484 
```
Only plain objects, and a few built-ins, can be passed to Client Components from Server Components. Classes or null prototypes are not supported.
<... request={{}} headers={{...}} cf=... params=... ctx=... rw=...>
```
This occurred because the layout wrapping logic was attempting to pass the `RequestInfo` object (containing non-serializable objects like `Request`, `Headers`, etc.) to client components, which violates React's RSC serialization constraints.
The `wrapWithLayouts` function was only checking if **layout components** were client components, but not checking if the **route component itself** was a client component. 
When …

fix: Prevent serialization errors when route components are client components

---

sdk/src/vite/createDirectiveLookupPlugin.mts

When searching for `use client` and `use server` in node modules, we also include ts, tsx and jsx in the search. If its in `node_modules`, we should just be checking for `{js,mjs,cjs}` - transpilation should have happened for code in packages.

fix: Only check for directives for {js,mjs,cjs} in node_modules

---

sdk/package.json
sdk/src/runtime/entries/clientSSR.ts
sdk/src/vite/configPlugin.mts

Currently, if `rwsdk/client` is imported in a `"use client"` component, this will cause us to evaluate code paths that were intended to only run in the browser in the cloudflare worker runtime environment too.
This plays out in unexpected ways. For example, `globalThis.__webpack_require__` (used for loading client components on both client side and SSR in worker) gets overridden to use the module loader meant for the browser.
* Remove the global `workerd` import condition from vite config: this way, resolutions in `client` environment now (correctly) do not follow `workerd` import conditions, but `ssr` and `worker` environments still do
* Change our `rwsdk/client` export conditions to point to a different entry point in the `workerd` case, so that SSR can get its own entry point for this …

fix: Separate entry point for rwsd/client during SSR

---

starters/minimal/README.md

Previous readme didn't include `-t minimal` which defaults to `standard`

docs: update minimal README to use minimal template

---

docs/src/content/docs/core/authentication.mdx

Removes the note about Quick Start using the minimal template from the _Authentication_ section. According to[ create-rwsdk](https://docs.rwsdk.com/reference/create-rwsdk/), the default command uses standard template.
> The [Quick Start Guide](https://docs.rwsdk.com/getting-started/quick-start) uses the minimal starter, you should use the standard starter to get you set up and ready for using Database, Queues, Sessions and Authentication.
**Caveat:** check if the standard starter still uses: Database, Queues, Sessions and Authentication. 👀 
If no, modify the note or the doc vs remove altogther.

docs: remove note

---

sdk/src/lib/getSrcPaths.ts
sdk/src/vite/createDirectiveLookupPlugin.mts

Currently, we scan all files in project for `use client` and `use server`. This PR uses the tsconfig to determine which paths to actually scan for these directives.

fix: Use tsconfig paths for directive scans

---

sdk/src/vite/configPlugin.mts

During builds, vite was building the SSR bridge module to a `.mjs` extension if the package.json of the project did not include `"type": "module"`, yet the RSC environment was looking for a .js extension for this module.
This PR fixes this by being explicit about the .js file extension.

fix: Ensure .js extension when resolving ssr bridge in builds

---

sdk/src/lib/getSrcPaths.ts
sdk/src/vite/createDirectiveLookupPlugin.mts

We were accidentally picking up dirs with .js extensions when scanning for directives.
Support thread: https://discord.com/channels/679514959968993311/1382098756081680464/1382098756081680464

fix: Skip dirs with .js extensions

---

docs/src/content/docs/tutorial/full-stack-app/3-database-setup.mdx

This pull request should fix #476 by updating the example `schema.prisma` with the current one from redwood starter.

docs: fix database tutorial

---

sdk/src/runtime/lib/router.ts
sdk/src/runtime/requestInfo/types.ts
sdk/src/runtime/worker.tsx
starters/minimal/src/worker.tsx

Added on all routing options the ability to have typesafe ctx via workers.tsx and router.ts and requestInfo
ie ```typescript
type MyCustomContext = {
foo: string;
bar: Array<number>;
baz: Record<string, number>;
}
const r = defineApp<RequestInfo<any, MyCustomContext>>([
route("/", ({ ctx }) => {
console.log(ctx.baz);
return new Response(ctx.foo);
}),
]);
```

Feat: Typesafe ctx

---

sdk/src/vite/createDirectiveLookupPlugin.mts
sdk/src/vite/hasDirective.mts
sdk/src/vite/transformClientComponents.mts
sdk/src/vite/transformServerFunctions.mts

In order to support RSC for the full module graph (including `node_modules`), we need to run the entire module graph through the `"use client"` and `"use server"` transformations. That said, we can still skip transformations as soon as we can tell that the given module has not "use server" or "use client" directive.
At the moment we exit early this way for "use client" - we first do a simple string check that the code starts with "use client" before parsing the code with ts-morph.
We currently do not do the same for "use server", which means every module in the graph (whether it is app code or code in node_modules) is first parsed with ts-morph.
This PR does the same as "use client" in the "use server" transform: first do a simple string check to test whether the code starts with "use …

feat: Avoid ts-morph parse for non-"use server" cases

---

sdk/src/runtime/client.tsx

This exposes `hydrationOptions` from `hydrateRoot`. This is required to turn off errors that occur when HTML rendering is disable. 
```tsx
import { initClient } from 'rwsdk/client'
initClient({ hydrationOtions: {...} })
```
cc: @jldec

Expose hydrateRoot options.

---

docs/astro.config.mjs
docs/src/content/docs/guides/frontend/client-side-nav.mdx
docs/src/content/docs/guides/frontend/tailwind.mdx
docs/src/content/docs/reference/sdk-client.mdx
sdk/src/runtime/clientNavigation.ts
sdk/src/runtime/entries/client.ts

This adds the ability for us to initialize client-side navigation, also known as single-page apps.
Docs: https://pp-client-navigation.redwood-sdk-docs.pages.dev/guides/frontend/client-side-nav/

Add client side navigation

---

docs/src/content/docs/reference/sdk-router.mdx

I liked @justinvdm's [loom](https://www.loom.com/share/0ba7ca7d375c403fb10959e28f7ede41?sid=131f0723-b1ec-4670-9aae-72a78d830e5a) so much that I thought including that detail in the docs might help other users understand the distinction between disabling server-side rendering of client components vs. server-side rendering of server-only components.

docs: clarify ssr render flag

---

sdk/src/vite/__snapshots__/transformServerFunctions.test.mts.snap
sdk/src/vite/transformServerFunctions.mts
sdk/src/vite/transformServerFunctions.test.mts

Since #521, there've been some issues with default exports in "use server" case:
```
// case 1: in this case, we were referencing `__defaultServerFunction__` even though it was not declared
const foo = () => 2 + 3;
export default foo;
// case 2: in this case
// * we were ending up with an unnecessary reference to `foo`
// * we were accidentally also re-exporting this as `foo` for worker case after transformation
export default function foo() {
return 2 + 3;
}
```
We also had redundant logic between client and ssr cases, and client logic was incomplete.

fix: default export fixes for server

---

sdk/src/runtime/lib/db/SqliteDurableObject.ts
sdk/src/runtime/lib/db/createDb.ts

Changes `createDb()` to start a warmup of the relevant durable object instance on first call. This allows us to run migrations as soon as possible for the DO, such that by the time DB interaction needs to happen, the DB is up and ready.
More context on what this DO db thing is all about coming soon!

feat: Warmup DO DB

---

sdk/src/vite/reactConditionsResolverPlugin.mts

We currently have a vite plugin for ensuring react resolves to the sdk's react deps. We do this so that we have control over what version react rwsdk is on in order to control stability while RSC and rwsdk are both being more stable.
We were doing `enforce: 'post'` for this vite plugin, and so some other plugin's resolveId was reaching resolutions for react before this plugin was. As a result, we'd end up getting resolving react to modules we weren't expecting, such as ones that might exist above the project dir if there are `node_modules` above the project dir.
Use `enforce: 'pre'` so that we're first in the chain.
* User issue: https://discord.com/channels/679514959968993311/1382564500527517706/1382725155322724394

fix: Ensure we resolve react relative to rwsdk package

---

sdk/src/scripts/ensure-deploy-env.mts

Add SIGINT handler to properly exit when user presses Ctrl+C
instead of continuing with deployment
When prompted "Do you want to proceed with deployment? (y/N):", pressing Ctrl+C doesn't properly cancel the deployment. The script continues running instead of exiting.
Added a SIGINT event handler to the readline interface that:
- Closes the readline interface
- Prints "Deployment cancelled." message
- Exits with code 1
This ensures Ctrl+C behaves as expected and cancels the deployment process.

fix: handle Ctrl+C gracefully during deployment prompt

---

docs/src/content/docs/tutorial/full-stack-app/4-auth.mdx
sdk/src/runtime/ssrBridge.ts

Nothing too crazy. I was going through the codebase and noticed the typo(s). Thanks for working on RedwoodSDK!
---
💖

fix(docs): drop extra ‘and’

---

sdk/src/runtime/render/renderRscThenableToHtmlStream.tsx

I added wrapper error info in #556 so that we include component stack. Part of that wrapper included a `Error Rendering RSC to HTML stream.` prefix to the underlying error message.
That prefixing ended up misleading people into thinking the actual error was `Error Rendering RSC to HTML stream` (#564). This PR removes that prefix to avoid this, but keeps the component stack info.

fix: Avoid misleading wrapper error message

---

sdk/src/scripts/debug-sync.mts
sdk/src/vite/directivesPlugin.mts
sdk/src/vite/findSsrSpecifiers.mts
sdk/src/vite/miniflareHMRPlugin.mts
sdk/src/vite/ssrBridgePlugin.mts
sdk/src/vite/transformClientComponents.mts

We have a concept of virtual SSR modules as part of the worker environment's module graph. Each corresponds to a module in the SSR environment's module graph.
This allows us to do processing for two different environments - most importantly, `worker` environment can use `react-server` import condition and RSC react runtime, `ssr` environment can use classic react runtime and _no_ `react-server` import condition.
In order to accomplish this, we have a vite `load()` plugin hook, which loads the virtual SSR modules in the worker env by calling `fetchModule` for the corresponding module in the SSR env.
We need to invalidate the virtual SSR module when the actual file changes, so that vite can reload it (as well as dependent modules in the graph) correctly with its changes accounted for. …

fix: SSR on explicit reloads after HMR

---

sdk/src/vite/miniflareHMRPlugin.mts
sdk/src/vite/ssrBridgePlugin.mts

To support SSR having its own module resolution behaviour (e.g. not using `react-server` import condition or RSC react runtimes) while still existing in the same runtime env as the rest of the worker (where `react-sever` import condition and RSC react runtimes should apply), we have separate `worker` and `ssr` environments, then have an "ssr bridge" concept: in the `worker` environment, for all modules to be evaluated in SSR context, we fetch code from the `ssr` environment for that module.
We parse the code we fetch from the SSR environment to find all imports vite does (`__vite_ssr_import__`, `__vite_ssr_dynamic_import__`), and add `import`s for these fetches so that vite will build the module graph correctly.
We do this fetching and transforming too for css modules too - except in …

fix: More HMR fixes for robustness

---

CONTRIBUTING.md
docs/src/content/docs/core/database-do.mdx
sdk/src/runtime/lib/db/SqliteDurableObject.ts
sdk/src/runtime/lib/db/createDb.ts
sdk/src/runtime/requestInfo/worker.ts
sdk/src/runtime/script.ts
sdk/src/scripts/debug-sync.mts
sdk/src/scripts/worker-run.mts

I needed to make several fixes and improvements to get the testimonials addon working: https://github.com/ahaywood/addon-testimonial/pull/1
We've designed [`createDb()`](https://f5069e4a.redwood-sdk-docs.pages.dev/core/database-do/#createdb) with the intention of being callable at the module level - this way one only needs to import `db`
Under the hood `createDb()` needs `requestInfo` to be around in order to hold onto some state for this db throughout the current request. However, `requestInfo` is not yet around at the point where `createDb()` is called.
This PR fixes this by having `createDb()` first wait for `requestInfo` to be around before trying to set state on it.
Since `rwsdb/db` databases are durable objects, the seed script needs a way to tell miniflare about the relevant DO …

Get rwsdk/db working with addon-testimonials

---

docs/src/content/docs/tutorial/full-stack-app/2-create-app.mdx
pnpm-lock.yaml
sdk/src/runtime/client.tsx
sdk/src/runtime/entries/auth.ts
sdk/src/runtime/entries/client.ts
sdk/src/runtime/entries/clientSSR.ts
sdk/src/runtime/entries/router.ts
sdk/src/runtime/entries/ssr.ts
sdk/src/runtime/entries/types/client.ts
sdk/src/runtime/entries/types/shared.ts
sdk/src/runtime/entries/types/ssr.ts
sdk/src/runtime/entries/types/worker.ts
sdk/src/runtime/entries/worker.ts
sdk/src/runtime/imports/client.ts
sdk/src/runtime/lib/auth/session.ts
sdk/src/runtime/lib/realtime/client.ts
sdk/src/runtime/lib/turnstile/useTurnstile.ts
sdk/src/runtime/register/worker.ts
sdk/src/runtime/worker.tsx
sdk/src/vite/devServerConstant.mts
sdk/src/vite/redwoodPlugin.mts
sdk/tsconfig.json
sdk/types/clientGlobal.d.ts
sdk/types/global.d.ts
starters/minimal/src/app/headers.ts
starters/standard/src/app/headers.ts
starters/standard/src/app/pages/user/functions.ts

So far, we've (I've) been been using `import.meta.DEV` to determine both:
* Is the the dev server running
* Is the application running in dev mode (`NODE_ENV=development`)
This is wrong of course, and breaks down in cases where one wants to use `NODE_ENV=development` in deployments or previews.
Why would one want to use `NODE_ENV=development` for deploys or previews? Use cases include easier debugging more dev info on staging deployments and vite previews.
We now no longer conflate the dev server running with whether `NODE_ENV=development` was given. We now have:
* `import.meta.env.VITE_IS_DEV_SERVER` - only true when the dev server is running (not a deployment or preview). Is independent of the value of `NODE_ENV=development` or the mode that vite is running in
* `import.meta.env.DEV` - …

fix: NODE_ENV=development deploys and previews

---

sdk/src/runtime/lib/realtime/durableObject.ts

For each realtime channel, we currently store the relevant url for each connected client, and use this when rendering clients on demand using `renderRealtimeClients()`. However, we weren't accounting for changes to the url done as a result of client navigation.
We already use each url we get for a client when client actions and navigations happen to determine how the client should be updated. We just need to store this latest url as the new url for usage with `renderRealtimeClient()`.

fix: renderRealtimeClients() usage with client navigation

---

sdk/src/vite/miniflareHMRPlugin.mts

Up till now, when errors happening during the dev workflow (e.g. if file was saved with syntax errors), you would see the error overlay screen until you manually reloaded the page.
We now detect we are in an error state, and trigger a full page reload on file changes if this is the case, which brings the app back to a working state if the error has now been fixed.
Fixes #410 
Fixes #412

fix: Recover from errors when doing HMR

---

docs/src/content.config.ts

Removed the top banner stating we are in preview mode since April 2025

docs: Removing banner configuration

---

sdk/src/runtime/requestInfo/types.ts
sdk/src/runtime/requestInfo/worker.ts
sdk/src/runtime/worker.tsx

I think that we need to consider adding this as an option. I don't know if this is the right way to go about it, but I wanted to start the conversation.
The `renderToString` and `renderToStream` methods are, I think, quite difficult to get right - and this is a quick win for us so that we can unblock @jldec.
I think I found better names for the request info object. I think we should call it HTTP messages. Which is what the Firefox manual refers to as request and response. I think we should also deprecate the headers and then just require that people set it on the actual response object.

Allow response status and headers to be modified.

---

sdk/src/vite/miniflareHMRPlugin.mts

We maintain lookups of client and server modules to use for client and ssr to be able to find and import these modules dynamically when they need to be used.
We make sure to add/remove from these lookups as files change (e.g. `"use client"` getting added to a module that did not have it). Problem is, when we did this adding/removing, we were not normalizing the paths - the lookups use vite style paths (`/src/app/Button.tsx`), but we were setting them as absolute paths (`/path/to/project/src/app/Button.tsx`)

fix: HMR for adding/removing "use client"

---

.github/workflows/smoke-test-starters.yml
docs/architecture/ssrBridge.md
sdk/scripts/release.sh
sdk/src/vite/findSsrSpecifiers.mts
sdk/src/vite/ssrBridgePlugin.mts

We have a concept of virtual SSR modules as part of the worker environment's module graph. Each corresponds to a module in the SSR environment's module graph.
This allows us to do processing for two different environments - most importantly, `worker` environment can use `react-server` import condition and RSC react runtime, `ssr` environment can use classic react runtime and _no_ `react-server` import condition.
In order to accomplish this, we have a vite `load()` plugin hook, which loads the virtual SSR modules in the worker env by calling `fetchModule` for the corresponding module in the SSR env.
Back in #586, we transformed code returned by these `fetchModule` calls, such that each import results in both a call to `__vite_ssr_import__`/`__vite_ssr_dynamic_import__` _and_ a `import()`. …

fix: Avoid double-import behaviour in dev for SSR modules

---

sdk/src/runtime/lib/db/DOWorkerDialect.ts
sdk/src/runtime/lib/db/createDb.ts
sdk/src/runtime/lib/db/index.ts

In Cloudflare Workers, each incoming event (e.g. an HTTP request or a Queue batch) runs inside its own isolated execution context. Any I/O object created in one event - including a Durable Object stub - can only be used in that same event. Attempting to use it in another event results in an error.
Previously, our database helper deferred creating the stub until the first time the database was accessed in a request. This was implemented using a Proxy around the database object.
While this approach delayed stub creation compared to doing it at module load time, it still created the stub earlier than necessary. The stub would be created when the database object was first touched in the request lifecycle, not when a query was actually executed.
In HTTP request handlers this generally worked, …

fix: `createDb()` in `queue()` handlers

---

sdk/src/runtime/lib/router.ts

The framework's routing API allows a route to return a React element, a `Response` object, or a promise that resolves to either. To handle this, a route is executed as a function inside a wrapper component. If the function returns a `Response`, it is handled via a rejection that is caught by the request handler to break out of the React rendering cycle.
In order for us to be sure we know whether `Response` was returned or not in all cases, in #630 we added a deferred that we block the response on, and only resolve/reject it once we know whether or not a response was returned from a component.
We only opt into this behaviour when we are dealing with _server_ components - since for client components, there is no possibility of returning a response instead in client components.
When checking …

fix: Response never returned for client components wrapped with layouts

---

sdk/src/runtime/lib/router.ts

The router runs a sequence of handlers for each request:
1) global middlewares
2) route matching
3) route-specific middlewares
4) final page component
Middlewares can return a Response, an element, or undefined. The final page component returns an element and may also return a Response.
- Global middlewares did not use the same element handling and render path as the page component. If a global middleware returned an element, it was not rendered as a page interruptor.
- Route-specific middlewares used duplicated logic intermixed with component handling, which made the flow unclear and caused the page component handling to run per iteration rather than once at the end.
- Layout wrapping was not clearly separated to only apply to the final page component.
This made interruptor-style …

Fix interruptors: render middleware elements; unify router flow

---

sdk/src/runtime/imports/client.ts

When using `render(..., { ssr: false })`, we wrap client components in order for their initial render result on mount to be `null`, so that we can match the hydrated RSC payload.
When doing this wrapping, we were not passing along the props passed to the wrapper.
As a result, client components used in server components did not get the props passed to them from those server components.
Fixes #583

fix: No props in client components when { ssr: false }

---

pnpm-lock.yaml
sdk/package.json

In [#653](https://github.com/redwoodjs/sdk/compare/link-to-pr-653), we changed rwsdk’s package.json to:
```json
"dependencies": {
"react": "19.2.0-canary-39cad7af-20250411",
"react-dom": "19.2.0-canary-39cad7af-20250411",
"react-server-dom-webpack": "19.2.0-canary-39cad7af-20250411"
},
"peerDependencies": {
"react": ">=19.2.0-0 || >=19.2.0",
"react-dom": ">=19.2.0-0 || >=19.2.0",
"react-server-dom-webpack": ">=19.2.0-0 || >=19.2.0"
},
"peerDependenciesMeta": {
"react": { "optional": true },
"react-dom": { "optional": true },
"react-server-dom-webpack": { "optional": true }
}
```
We did this for backwards compat: users could keep what they had, but also take control of React deps by adding them themselves, instead of being locked to the versions pinned in rwsdk.
With pnpm, this setup does …

fix: Change react deps to optional

---

sdk/src/scripts/worker-run.mts
sdk/src/vite/redwoodPlugin.mts

Currently, one is able to specify a custom config path for their wrangler config in our vite plugin, but not with `worker-run` scripts. We need to be able to specifying the wrangler config in both cases.
Change both the vite pugin and `worker-run` to make use of a `RWSDK_WRANGLER_CONFIG` env var to specify the wrangler config path.
Went fr env var instead of a cli arg, so that it can be propagated more easily to the different parts that need to know the worker config path.
```bash
RWSDK_WRANGLER_CONFIG=... pnpm dev:init
RWSDK_WRANGLER_CONFIG=... pnpm dev
```
Solves #636

feat: Allow specifying wrangler config via env var

---

docs/src/content/docs/core/authentication.mdx

Changed `language` prop to `lang` based on [Expressive Code documentation](https://expressive-code.com/key-features/code-component/#available-props)
Before:
After:

🐛 Fixed code highlighting

---

.worklogs/justin/2025-09-03-fix-vite7-scanner-resolution.md
sdk/src/vite/createViteAwareResolver.mts

To discover `"use client"` and `"use server"` directives, we perform a pre-scan of the project using a lightweight, `esbuild`-based scanner. To ensure this scan respects custom module paths (e.g., from `vite-tsconfig-paths`), its resolver implements a simplified subset of Vite's logic, calling the `resolveId` hooks from the project's configured plugins.
For projects on Vite 7, this scanner would crash. The issue was an incompatibility with Vite 7's new plugin architecture; our resolver was executing `resolveId` handlers directly while bypassing the new `filter` property that scopes their execution. This caused it to incorrectly resolve the `worker.tsx` entry point to `vite/modulepreload-polyfill.js`, which `esbuild` cannot process.
For each plugin's `resolveId` hook, if the new …

fix: Directive scanner compatibility with vite 7

---

.worklogs/justin/2025-09-04-context-aware-directive-scan.md
docs/architecture/directiveScanningAndResolution.md
sdk/src/vite/runDirectivesScan.mts

The framework requires a complete list of all modules containing `"use client"` and `"use server"` directives before the main build/dev process begins. To accomplish this, we use a custom `esbuild`-based scanner that traverses the dependency graph ahead of Vite's own machinery.
The previous implementation of this scanner used a single, static resolution strategy. It would determine the environment (e.g., "worker") from the initial entry point and use that context for the entire scan. This created a problem when the dependency graph crossed an environment boundary. For example, a server-side entry point would import a component with a `"use client"` directive. The scanner would fail to switch its context and would continue to use "worker" conditions (like `"react-server"`) to resolve the …

fix: Respect server and client environments when scanning for directives

---

sdk/src/vite/buildApp.mts
sdk/src/vite/createViteAwareResolver.mts
sdk/src/vite/directiveModulesDevPlugin.mts
sdk/src/vite/runDirectivesScan.mts

#675 added the ability to switch between resolving as worker, or resolving as client, depending on whether in the traversal context we are currently "in" client modules or server modules.
It went for a very limited approach to using client resolvers though - instead of using the full client env's config for resolution, it just set the import conditions only.
This PR uses the actual client environment for resolving for the client.

fix: Use more complete client resolver

---

sdk/src/runtime/entries/worker.ts
sdk/src/runtime/imports/resolveSSRValue.ts
sdk/src/runtime/register/worker.ts
sdk/src/vite/buildApp.mts
sdk/src/vite/createViteAwareResolver.mts
sdk/src/vite/directiveModulesDevPlugin.mts
sdk/src/vite/runDirectivesScan.mts

Sometimes one needs to use dependencies that use react-dom/server themselves. For example, resend uses `@react-email/render`, which uses `react-dom`.
Trouble is, if we have these imports around in on the worker side, the `react-server` import condition we need to use on the worker side for RSC will cause `react-dom/server` to resolve to a dummy module that throws with `"react-dom/server is not supported in React Server Components"`. React does this intentionally - since RSC react packages have their own separate runtime compared to 'normal" React.
As a result, naively bundling with resend will cause that `"react-dom/server is not supported in React Server Components"` runtime error.
We already have an [SSR bridge](https://github.com/redwoodjs/sdk/blob/0f7ba26a939eaa80f907d4883e50d2d55e0f98 …

feat: Support importing SSR-based dependencies in worker env

---

pnpm-lock.yaml
starters/minimal/package.json
starters/standard/package.json

Now that we are pinning deps for our starters, our CF worker types defs need to be newer versions to be compatible with the wrangler version we have pinned.

fix: Update starter worker types

---

playground/hello-world/vite.config.mts
playground/render-apis/vite.config.mts
playground/useid-test/vite.config.mts

This change addresses an intermittent failure in the end-to-end tests caused by inspector port collisions. When multiple dev server tests run in parallel, they would sometimes attempt to bind to the same default inspector port, leading to a race condition and test failures.
The fix is to disable the inspector port within the Vite configuration for all playground applications when the CI environment variable is set. This prevents the port conflict during automated testing while keeping the inspector available for local development.

fix(e2e): Disable inspector port in tests to prevent collisions

---

.notes/justin/worklogs/2025-09-24-vite-esbuild-yarn-resolution-issue.md
sdk/src/vite/configPlugin.mts
sdk/src/vite/knownDepsResolverPlugin.mts

The dev server would crash with the error `Internal server error: There is a new version of the pre-bundle...` during development.
This was a side effect of a fix in PR #775. To support 'use client' and 'use server' directives in third-party packages, our build process transforms code in `node_modules`, which requires injecting imports to `rwsdk` modules. In a monorepo, a transformed dependency can be hoisted to the root, while the `rwsdk` package itself is located in a nested project's `node_modules`.
To handle this inverted resolution path, we introduced custom resolution logic in a vite plugin in RedwoodSDK. While this fixed the resolution failure, it revealed a limitation in Vite's dependency scanner. Once Vite could find an initial `rwsdk` module, its static analysis could not always …

fix(vite): Prevent re-optimization by defining all framework dependencies

---

docs/src/content/docs/core/overview.mdx

Resolves: #810 
Updated the database link on the overview page to the correct URL  (https://docs.rwsdk.com/core/database-do/)

fix(docs): update database url on overview page
