- experiments/rsc/scripts/lib/configs.mts
- experiments/rsc/src/app/App.tsx
- experiments/rsc/src/app/HomePage.tsx
- experiments/rsc/src/app/components/Like.tsx
- experiments/rsc/src/client.tsx
- experiments/rsc/tsconfig.json
https://www.loom.com/share/f43f34f308544ab780750c36ac3015c0
> Add client side hydration.

- experiments/rsc/scripts/build.mts
- experiments/rsc/scripts/lib/configs.mts
- experiments/rsc/scripts/lib/constants.mts
- experiments/rsc/scripts/lib/transformJsxScriptTagsPlugin.mts
- experiments/rsc/scripts/runDevServer.mts
- experiments/rsc/wrangler.toml
https://www.loom.com/share/9802a6f962064e32ac2110c76ac0c665?sid=e214cc1a-95e9-42ef-b7f2-2df88006933c
> feat: Resolve client assets in deployment builds

- experiments/billable/scripts/lib/vitePlugins/miniflarePlugin/plugin.mts
We lost loading of .env in #46, this brings it back.
> fix: Bring .env loading back

- experiments/billable/scripts/configs/vite.mts
- experiments/textify/scripts/buildVendorBundles.mts
- experiments/textify/scripts/configs/vite.mts
- experiments/textify/scripts/firstRun.mts
- experiments/textify/scripts/lib/constants.mts
- experiments/textify/scripts/lib/vitePlugins/aliasByEnvPlugin.mts
- experiments/textify/scripts/lib/vitePlugins/miniflarePlugin/plugin.mts
- experiments/textify/scripts/lib/vitePlugins/miniflarePlugin/worker.mts
- experiments/textify/scripts/lib/vitePlugins/useClientPlugin.mts
- experiments/textify/scripts/runDevServer.mts
- experiments/textify/vendor/src/react-dom-server-edge.js
- experiments/textify/vendor/src/react-server-internals.js
- experiments/textify/vendor/src/react-ssr.ts
- experiments/textify/vendor/src/react.js
Copy over the scripts from billable experiment to textify to get them up to date.
(We'll soon need to abstract out these scripts to use them across the projects, but until then this works)
> chore: Update textify scripts/

- experiments/billable/src/app/pages/Layout.tsx
- experiments/billable/src/app/pages/auth/functions.ts
- experiments/billable/src/app/pages/invoice/DetailPage/InvoiceForm.tsx
- Do not display logo upload if not logged in.
- Also provide the token in the email to enter manually.
> Billable, small tweaks.

- experiments/yt-dos/src/app/pages/Home/SearchTerminal.tsx
remove recommendations after playing a video, I don't want people to go into the rabbit hole.
> remove yt recomendations

- starters/prisma/src/app/pages/Home.tsx
In order to get the prisma starter working, I needed to change `Home` to `await` the `db.user.findMany()` call.
Otherwise, worked perfectly :)
> fix: Await db.users.findMany()

- docs/astro.config.mjs
- docs/src/content/docs/core/authentication.mdx
A first iteration on auth docs - very likely needs more work, but its a start.
> docs: First pass on auth docs

- docs/astro.config.mjs
- docs/ec.config.mjs
- docs/package.json
- docs/src/content/docs/getting-started/quick-start.mdx
- docs/src/content/docs/reference/routing.mdx
- pnpm-lock.yaml
- starters/standard/README.md
- starters/standard/src/worker.tsx
- Add collapsible sections.
- Improve quickstart.
- Rename these things slightly.
- Highlight correct line.
- Add line numbers.
> Rework docs for "standard."

- docs/src/content/docs/core/authentication.mdx
- starters/standard/src/app/pages/auth/LoginPage.tsx
With the change of direction described in #162, this PR rewrites the auth docs to match that direction.
> docs: Rewrite auth for standard starter

- docs/src/content/docs/index.mdx
I *think* this is what you wanted to say. If not, feel free to just close the PR 🫡
> docs(index): Minor tweak to messaging

- .github/workflows/check-sdk.yml
- sdk/src/vite/useClientPlugin.mts
Change github workflow to build sdk (after which we run tests) to make sure we dont have type issues in PRs.
> chore: Build sdk on PRs if sdk src changes

- sdk/src/runtime/lib/realtime/durableObject.ts
- sdk/src/runtime/lib/realtime/validateUpgradeRequest.ts
- sdk/src/runtime/lib/realtime/worker.ts
- sdk/src/runtime/worker.tsx
* Check request origin header for upgrade requests
* Make sure DO responses proxied by worker include headers added by worker
* Remove unnecessary logging
> fix: Security improvements for realtime

- docs/astro.config.mjs
- docs/package.json
- pnpm-lock.yaml
Added google analytics so we can measure whats happening on the docs pages
Domain is now [https://docs.rwsdk.com](https://docs.rwsdk.com)
> add GA4 to astro SDK docs

- docs/astro.config.mjs
needed site for sitemap work correctly
> add site for sitemap

- docs/README.md
Cleaning up an accidentally added character
> chore(docs): Remove stray character

- docs/src/content/docs/getting-started/quick-start.mdx
- docs/src/content/docs/index.mdx
- docs/src/styles/custom.css
- Hide table of contents.
- Format CSS.
- Fix quick start styling.
> Documentation tweaks

- docs/src/content/docs/core/realtime.mdx
- docs/src/content/docs/index.mdx
* real-time => realtime
* add DO adding step
> docs: Small docs fixes for realtime

- sdk/package.json
- starters/drizzle/package.json
- starters/minimal/package.json
- starters/passkey-auth/package.json
- starters/prisma/README.md
- starters/prisma/package.json
- starters/sessions/package.json
- starters/standard/package.json
* Add keywords for sdk package.json
* Add descriptions to sdk and starters in package.json
> chore: Add package.json keywords and descriptions

- docs/astro.config.mjs
- docs/src/styles/custom.css
1. increased the font size for desktop and mobile layouts, it was to small
> increase font-size

- docs/src/content/docs/core/react-server-components.mdx
- docs/src/content/docs/core/realtime.mdx
- docs/src/content/docs/core/routing.mdx
- docs/src/content/docs/core/security.mdx
- docs/src/content/docs/getting-started/first-project.mdx
Follow up to #251 for updating docs.
> docs: Update docs after change to requestInfo

- docs/astro.config.mjs
the image link was not working
> fix OG image link

- README.md
- docs/README.md
Added logo and links to the Readme pages
> add logo and links to readme files

- sdk/src/runtime/lib/realtime/renderRealtimeClients.ts
> fix: Types for renderRealtimeClients

- starters/standard/wrangler.jsonc
> chore: Migrate to sqlite-backed DOs

- docs/astro.config.mjs
create consistent meta tags across.
We use this prefer description:
**RedwoodSDK is a React Framework for Cloudflare. 
It begins as a Vite plugin that unlocks SSR, React Server Components, Server Functions, and realtime features.  Its standards-based router, with support for middleware and  interruptors, gives you fine-grained control over every request and  response**
> update meta description for consistency

- sdk/src/runtime/lib/realtime/client.ts
- sdk/src/runtime/lib/realtime/durableObject.ts
At the moment, the sdk's realtime API doesn't check whether a chunk it is receiving is related to the current update it is busy with. As a result, responses' chunks can get mixed up if sent in quick succession to the client.
Generate and send id's each chunk.
* For actions - we check if the id matches the action's request id
* For rsc updates, we check that chunks received matched the id of the first chunk received
> fix: Add and check ids for each realtime chunk

- sdk/src/runtime/worker.tsx
We support pages returning either an element, or a response. The way we do this, is by simply calling the page component as a function, and inspecting whether the result is an element or a response
The issue with simply calling the page component, is that this happens _outside of the react rendering context_. React does some set up to its internal state at the beginning of rendering. I think it is likely we will run into issues because of this. e.g. if there are RSC-valid hook usages (e.g. `use()`) or maybe even `Suspense`s.
We want to avoid unrolling this first level in the component tree and leave this up to react.
We can do this by wrapping around the component, and calling it within the wrapper. If we are instantiating the wrapper as a react element and leaving react to unroll it, …
> fix: More robust Page: () => Element | Response

- .vscode/settings.json
- docs/astro.config.mjs
- docs/src/content/docs/guides/frontend/documents.mdx
- docs/src/content/docs/guides/frontend/layouts.mdx
- docs/src/content/docs/guides/frontend/metadata.md
- docs/src/content/docs/guides/frontend/public-assets.mdx
- docs/src/content/docs/guides/frontend/shadcn.mdx
- docs/src/content/docs/guides/frontend/tailwind.mdx
Added documentation for Layouts, Documents, Public Assets, ShadCN, and Tailwind
> ✨ Doc Updates (Tailwind, ShadCN, Documents, Assets, and Layouts)

- docs/src/content/docs/core/queues.mdx
small fix on the queue consumer example in the docs that seems to be outdated
[Cloudflare doc for reference](https://developers.cloudflare.com/queues/get-started/#4-create-your-consumer-worker)
> docs: fix queues consumer example in queues.mdx

- pnpm-lock.yaml
- sdk/package.json
- starters/minimal/package.json
- starters/standard/package.json
> chore: Upgrade @cloudflare/vite-plugin 1.0.1 -> 1.1.0 + wrangler 4.8.0 -> 4.14.1

- README.md
- sdk/README.md
I have updated the README to show how to get started, and some features to be found in the docs pages.
> update the readme

- sdk/src/runtime/render/injectRSCPayload.ts
> fix: preserve UTF-8 integrity in `injectRSCPayload` by streaming `TextDecoder`

- sdk/src/lib/smokeTests/browser.mts
- sdk/src/lib/smokeTests/development.mts
- sdk/src/lib/smokeTests/release.mts
- sdk/src/lib/smokeTests/reporting.mts
- sdk/src/lib/smokeTests/runSmokeTests.mts
- sdk/src/lib/smokeTests/state.mts
- sdk/src/lib/smokeTests/templates/SmokeTest.template.tsx
- sdk/src/lib/smokeTests/templates/SmokeTestClient.template.tsx
- sdk/src/lib/smokeTests/templates/smokeTestFunctions.template.ts
- sdk/src/lib/smokeTests/types.mts
- sdk/src/scripts/smoke-test.mts
Updates our smoke tests to modify server and client components (for both realtime and non-realtime cases), and check that the changes applied.
> feat: Support checking HMR in Smoke Tests

- docs/package.json
- docs/src/content/docs/core/overview.mdx
- pnpm-lock.yaml
- Added `astro-embed` to package.json.
- Integrated YouTube embedding functionality in the overview documentation.
- Updated pnpm-lock.yaml with new package versions and dependencies.
> ✨ Update dependencies and enhance documentation with new features

- docs/src/content/docs/reference/sdk-router.mdx
- sdk/src/runtime/lib/router.ts
- sdk/src/runtime/worker.tsx
> Add disable RSC flight option

- sdk/src/runtime/lib/router.test.ts
- sdk/src/runtime/lib/router.ts
Closes #312
I tried to make this work with the `URLPattern` API, but wasn't successful. I'll take another look at it when I get more time.
> Fix URL pattern matching

- docs/README.md
- docs/src/content/docs/core/database.mdx
- docs/src/content/docs/index.mdx
- docs/src/content/docs/tutorial/full-stack-app/2-create-app.mdx
Migrated to the `npx create-rwsdk <project-name>` command
Full repo here: https://github.com/ahaywood/create-rwsdk
> ✨ Migrated to npx create-rwsdk command

- docs/src/content/docs/guides/frontend/shadcn.mdx
- docs/src/content/docs/tutorial/full-stack-app/2-create-app.mdx
- Removed baseUrl
- Removed @ alias in vite config
> 🔼 Updated documentation and tutorial for v0.0.85

- docs/src/content/docs/tutorial/full-stack-app/9-deploying.mdx
Add missing steps to create D1 database
> Update doc 'tutorial/full-stack-app/9-deploying.mdx'

- sdk/src/runtime/lib/router.ts
RedwoodSDK's router currently lacks support for shared UI layouts, forcing developers to manually wrap components or duplicate layout code across routes. This makes it difficult to:
1. **Create consistent page structures** - No way to share headers, sidebars, footers across routes
2. **Implement nested layouts** - Complex applications need multiple layout levels (App > Admin > Dashboard)
3. **Organize routes logically** - Related routes can't easily share layout components
4. **Avoid code duplication** - Layout code gets duplicated across route handlers
Introduce a `layout()` function that wraps routes with layout components, similar to React Router's nested layouts but designed for RedwoodSDK's server-side routing approach.
```tsx
layout(LayoutComponent: React.FC<LayoutProps>, routes: …
```
> feat: Add layout function

- docs/src/content/docs/guides/frontend/layouts.mdx
- Updated Layout docs based on #479
> 📝 docs: Updated frontend/layout docs

- docs/astro.config.mjs
- docs/src/content/docs/reference/create-rwsdk.mdx
- Explained how the `create-rwsdk` command works.
- Included details about some of the flags
> ✨ docs: create-rwsdk command

- sdk/src/lib/hasPkgScript.mts
- sdk/src/scripts/dev-init.mts
- sdk/src/vite/redwoodPlugin.mts
> fix: Only run dev:init if script exists

- pnpm-lock.yaml
- sdk/package.json
- sdk/src/runtime/lib/db/DOWorkerDialect.ts
- sdk/src/runtime/lib/db/SqliteDurableObject.ts
- sdk/src/runtime/lib/db/createDb.ts
- sdk/src/runtime/lib/db/index.ts
- sdk/src/runtime/lib/db/migrations.ts
- sdk/src/runtime/lib/debug.ts
- sdk/src/runtime/lib/router.ts
- sdk/src/runtime/requestInfo/types.ts
- sdk/src/runtime/worker.tsx
- starters/minimal/package.json
- starters/standard/package.json
Video with context: https://www.loom.com/share/22ea1d8d2f704d8bb73f06c645eeb1db
**note:** Video currently incomplete, ran out of time, will cover the rest soon and add it onto this ^ video.
Text context coming soon!
> feat: DO-based DBs initial implementation

- docs/src/content/docs/tutorial/full-stack-app/2-create-app.mdx
fixing the path annotation on the code block
> fixing the path annotation on the code block from `.../auth/Login.tsx` to `.../user/Login.tsx`

- docs/src/content/docs/tutorial/full-stack-app/5-jobs-list.mdx
Updated 5-jobs-list.mdx tutorial snippets to match the actual code.
> docs: Fix minor inconsistencies in 5-jobs-list.mdx

- sdk/src/runtime/lib/router.ts
- A recent change ([PR #645]) ran all global middlewares in a first pass before route matching.
- This caused middlewares to run that should not have been called:
- If multiple render middlewares existed, the next one could run even when an earlier route would have matched.
- Breaking on the first non-function entry could stop iteration early if that route did not match, skipping middlewares and later matches.
- Middlewares that returned elements were not consistently rendered through the same page render path as components.
- Replace the two-pass approach with a single pass over the flattened routes:
- For each entry:
- If middleware: execute it. Response → return; element → render via the standard page render path; otherwise continue.
- If route definition: try to match. If not matched, …
> fix: Restore old router behavior of short-circuiting on first match

- sdk/src/vite/miniflareHMRPlugin.mts
A unique challenge arises from how stylesheet imports are processed in the development server's SSR environment. When a client component imports a CSS file, that import travels through the [SSR Bridge](./ssrBridge.md), which must correctly handle it. If not managed properly, plugins like Tailwind CSS might try to parse transformed JavaScript (from a CSS module) as if it were raw CSS, causing build failures.
This problem is orthogonal to injecting stylesheet links into the `<head>`. It is about ensuring that `import styles from './Button.module.css'` works correctly during server-side rendering, providing the component with the correct class name hashes for the initial HTML.
To solve this, we performs a specific transformation when processing for the ssr bridge:
1.  **Identifier …
> fix: HMR for SSR'd css modules

- docs/src/content/docs/core/routing.mdx
> docs: Fix syntax soup in routing docs

- docs/astro.config.mjs
- docs/src/content/docs/guides/optimize/react-compiler.mdx
This guide shows how to install React compiler
> docs: Guide to install React compiler

- docs/src/content/docs/guides/frontend/tailwind.mdx
Fixes code highlighting issues for the Tailwind guide in the docs to highlight the lines being added.
> Fixes code highlighting issues for tailwind guide

- .worklogs/justin/2025-09-04-context-aware-directive-scan.md
- sdk/src/vite/runDirectivesScan.mts
A previous refactoring in #675 to clean up the directive scanner was overly aggressive. It removed logic from the `esbuild` plugin's `onLoad` hook that was responsible for determining and caching a module's environment. By correctly determining and caching a module's own environment when it is loaded, we ensure that the resolution context is propagated correctly throughout the entire dependency graph.
> fix: Store module env correctly in directive scanner

- docs/src/content/docs/guides/frontend/shadcn.mdx
Tweaked shadcn docs
- Order matches shadcn/ui documentation
> 📝 shadcn docs: path update, note combination, steps rearrange

- .github/workflows/smoke-test-starters.yml
- .worklogs/justin/2025-09-10-smoke-test-matrix.md
- sdk/src/lib/smokeTests/development.mts
- sdk/src/lib/smokeTests/environment.mts
- sdk/src/lib/smokeTests/types.mts
- sdk/src/scripts/debug-sync.mts
- sdk/src/scripts/smoke-test.mts
This PR introduces a smoke test matrix to run our smoke tests across different OSes and package managers: `[linux, windows] x [pnpm, npm, yarn berry, yarn classic]`
> tests: Smoke test matrix

- .github/workflows/playground-e2e-tests.yml
- .github/workflows/smoke-test-starters.yml
- .notes/justin/worklogs/2025-09-20-ci-improvements.md
- scripts/cleanup-test-workers.sh
- scripts/quick-cleanup.sh
- scripts/retry.sh
* We now allow retries for each cell in the (OS, package manager) test matrix for smoke tests and e2e tests
* We've now added macos to test matrix for smoke tests and e2e tests
> infra: CI improvements
